"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
const labels={pending_review:"Waiting for pharmacy review",confirmed:"Order confirmed",preparing:"Being prepared",ready:"Ready for pickup / dispatch",out_for_delivery:"Out for delivery",delivered:"Delivered",cancelled:"Cancelled",rejected:"Rejected"};
const steps=["pending_review","confirmed","preparing","ready","out_for_delivery","delivered"];
export default function OrderTrackingPage({params}){
 const[token,setToken]=useState(""),[order,setOrder]=useState(null),[error,setError]=useState("");
 useEffect(()=>{Promise.resolve(params).then(p=>setToken(p?.token||""))},[params]);
 useEffect(()=>{if(!token)return;let active=true;const load=()=>fetch(`/api/online-orders/${token}`,{cache:"no-store"}).then(r=>r.json()).then(d=>{if(!active)return;if(!d.success)throw new Error(d.error);setOrder(d.order)}).catch(e=>active&&setError(e.message||"Unable to load order."));load();const id=setInterval(load,20000);return()=>{active=false;clearInterval(id)}},[token]);
 if(error)return <main style={s.page}><div style={s.card}><h1>Order not found</h1><p>{error}</p><Link href="/online-order" style={s.button}>Back to store</Link></div></main>;
 if(!order)return <main style={s.page}><div style={s.card}>Loading order…</div></main>;
 const current=steps.indexOf(order.order_status);
 return <main style={s.page}><div style={s.card}><div style={s.kicker}>DHIMAN MEDICOS</div><h1>Order {order.order_number}</h1><p style={s.muted}>Placed {new Date(order.created_at).toLocaleString("en-IN")}</p><div style={s.status}><strong>{labels[order.order_status]||order.order_status}</strong><span>{order.payment_status==="paid"?"Payment received":"Payment pending"}</span></div><div style={s.timeline}>{steps.map((step,i)=><div key={step} style={s.item}><div style={{...s.dot,opacity:i<=current?1:.28}}>{i<=current?"✓":""}</div><div><strong>{labels[step]}</strong>{order.events?.filter(e=>e.status===step).slice(-1).map(e=><small key={e.created_at}>{e.note}</small>)}</div></div>)}</div><section style={s.section}><h2>Items</h2>{order.items.map(i=><div key={i.medicine_name} style={s.row}><span>{i.medicine_name} × {i.quantity}</span><strong>₹{Number(i.line_total).toFixed(2)}</strong></div>)}<div style={{...s.row,borderTop:"1px solid #ddd",paddingTop:10,marginTop:8}}><strong>Total</strong><strong>₹{Number(order.total).toFixed(2)}</strong></div></section>{order.delivery_method==="delivery"&&<section style={s.section}><h2>Delivery</h2><p>{order.address_line1}{order.address_line2?`, ${order.address_line2}`:""}{order.landmark?`, ${order.landmark}`:""}<br/>{order.city}, {order.state} — {order.pincode}</p></section>}{order.prescription_status!=="not_required"&&<div style={s.notice}>📋 Prescription: <strong>{order.prescription_status}</strong></div>}<div style={s.actions}><Link href="/online-order" style={s.button}>Order more medicines</Link><Link href="/" style={s.secondary}>Storefront</Link></div></div></main>;
}
const s={page:{minHeight:"100vh",padding:20,background:"#faf7f0",fontFamily:"Inter,system-ui,sans-serif",color:"#16241b"},card:{maxWidth:650,margin:"5vh auto",background:"#fffdf9",border:"1px solid #e7e0cf",borderRadius:22,padding:24,boxShadow:"0 10px 35px rgba(11,42,28,.08)"},kicker:{fontSize:11,fontWeight:900,letterSpacing:2,color:"#0e5938"},muted:{color:"#6f7a70"},status:{display:"flex",justifyContent:"space-between",gap:10,padding:14,borderRadius:14,background:"#edf5ef",margin:"18px 0",flexWrap:"wrap"},timeline:{display:"grid",gap:13,margin:"18px 0 25px"},item:{display:"grid",gridTemplateColumns:"34px 1fr",gap:10,alignItems:"start"},dot:{width:28,height:28,borderRadius:"50%",background:"#0e5938",color:"white",display:"grid",placeItems:"center",fontWeight:900},section:{borderTop:"1px solid #e5e1d6",paddingTop:16,marginTop:14},row:{display:"flex",justifyContent:"space-between",gap:12,padding:"6px 0"},notice:{marginTop:15,padding:12,borderRadius:12,background:"#fff6e8",color:"#7d5620"},actions:{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10,marginTop:20},button:{display:"flex",justifyContent:"center",alignItems:"center",padding:12,borderRadius:12,background:"#0e5938",color:"white",fontWeight:800,textDecoration:"none"},secondary:{display:"flex",justifyContent:"center",alignItems:"center",padding:12,borderRadius:12,border:"1px solid #d8ded8",color:"inherit",fontWeight:800,textDecoration:"none"}}
