import { NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";
import { createServerClient } from "@supabase/ssr";
import { createHash, randomUUID } from "crypto";

export const dynamic = "force-dynamic";
export const runtime = "nodejs";
const BUCKET="prescriptions", MAX_SIZE=10*1024*1024;
const ALLOWED_MIME_TYPES=new Set(["image/jpeg","image/png","image/webp","image/heic","image/heif","application/pdf"]);
const MIME_BY_EXTENSION={jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",webp:"image/webp",heic:"image/heic",heif:"image/heif",pdf:"application/pdf"};
function getAdmin(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error("Supabase server configuration is missing.");return createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}})}
async function getUser(request){const response=NextResponse.next();const supabase=createServerClient(process.env.NEXT_PUBLIC_SUPABASE_URL,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,{cookies:{getAll(){return request.cookies.getAll()},setAll(){}}});const {data:{user}}=await supabase.auth.getUser();return user||null;}
function mime(file){if(file.type&&ALLOWED_MIME_TYPES.has(file.type))return file.type;return MIME_BY_EXTENSION[String(file.name||"").split(".").pop().toLowerCase()]||""}
function safeFilename(name){return String(name||"prescription").normalize("NFKC").replace(/[^a-zA-Z0-9._-]/g,"_").replace(/_+/g,"_").slice(0,180)}
export async function POST(request){try{const user=await getUser(request);if(!user)return NextResponse.json({success:false,error:"Please sign in before uploading a prescription."},{status:401});const fd=await request.formData(),file=fd.get("file");if(!file||typeof file.arrayBuffer!=="function")return NextResponse.json({success:false,error:"Please select a prescription file."},{status:400});if(file.size<=0||file.size>MAX_SIZE)return NextResponse.json({success:false,error:"Prescription must be between 1 byte and 10 MB."},{status:400});const mimeType=mime(file);if(!ALLOWED_MIME_TYPES.has(mimeType))return NextResponse.json({success:false,error:"Unsupported prescription format."},{status:400});const buffer=Buffer.from(await file.arrayBuffer()),sha256=createHash("sha256").update(buffer).digest("hex"),originalFilename=String(file.name||"prescription"),filePath=`uploads/${Date.now()}-${randomUUID()}-${safeFilename(originalFilename)}`,supabase=getAdmin();const {error:uploadError}=await supabase.storage.from(BUCKET).upload(filePath,buffer,{contentType:mimeType,cacheControl:"31536000",upsert:false});if(uploadError)throw uploadError;const {data,error:dbError}=await supabase.from("prescriptions").insert({file_path:filePath,original_filename:originalFilename,mime_type:mimeType,file_size:file.size,sha256,status:"pending",user_id:user.id}).select("id,original_filename,mime_type,file_size,sha256,status,created_at").single();if(dbError){await supabase.storage.from(BUCKET).remove([filePath]);throw dbError;}return NextResponse.json({success:true,prescription:data});}catch(error){console.error("Prescription upload error:",error);return NextResponse.json({success:false,error:error?.message||"Prescription upload failed."},{status:500})}}
export async function GET(request){try{const user=await getUser(request);if(!user)return NextResponse.json({success:false,error:"Authentication required."},{status:401});const id=Number(new URL(request.url).searchParams.get("id"));if(!Number.isInteger(id)||id<=0)return NextResponse.json({success:false,error:"Invalid prescription ID."},{status:400});const supabase=getAdmin();const {data,error}=await supabase.from("prescriptions").select("id,file_path,original_filename,mime_type,file_size,sha256,status,created_at,sale_id,user_id").eq("id",id).single();if(error||!data)return NextResponse.json({success:false,error:"Prescription not found."},{status:404});const isAdmin=user.app_metadata?.role==="admin";if(!isAdmin&&data.user_id!==user.id)return NextResponse.json({success:false,error:"Prescription access denied."},{status:403});const {data:signed,error:signedError}=await supabase.storage.from(BUCKET).createSignedUrl(data.file_path,300);if(signedError)throw signedError;return NextResponse.json({success:true,prescription:{...data,url:signed.signedUrl}})}catch(error){console.error("Prescription retrieval error:",error);return NextResponse.json({success:false,error:error?.message||"Unable to open prescription."},{status:500})}}
