create table if not exists public.univentis_product_metadata (
  id bigint generated by default as identity primary key,
  medicine_id text not null,
  product_name text not null,
  source_url text not null,
  manufacturer text not null default 'Univentis Medicare Limited',
  division text,
  composition text,
  formulation text,
  therapy text,
  pack_size text,
  reference_mrp numeric(12,2),
  status text,
  description text,
  match_method text not null default 'exact_normalized_name',
  match_confidence numeric(5,4) not null default 1.0000 check (match_confidence >= 0 and match_confidence <= 1),
  raw_source jsonb not null default '{}'::jsonb,
  fetched_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (medicine_id),
  unique (source_url)
);
create index if not exists idx_univentis_product_metadata_name on public.univentis_product_metadata (lower(product_name));
create index if not exists idx_univentis_product_metadata_fetched_at on public.univentis_product_metadata (fetched_at desc);
alter table public.univentis_product_metadata enable row level security;
drop policy if exists "univentis metadata authenticated read" on public.univentis_product_metadata;
create policy "univentis metadata authenticated read" on public.univentis_product_metadata for select to authenticated using (true);

create table if not exists public.cipla_product_metadata (
  id bigint generated by default as identity primary key,
  medicine_id text not null,
  product_name text not null,
  source_url text not null,
  source_system text not null default 'ciplamed',
  manufacturer text not null default 'Cipla Limited',
  brand_name text,
  molecule text,
  composition text,
  formulation text,
  dosage_form text,
  therapy text,
  pack_size text,
  reference_mrp numeric(12,2),
  status text,
  description text,
  product_page_url text,
  match_method text not null default 'exact_normalized_name',
  match_confidence numeric(5,4) not null default 1.0000 check (match_confidence >= 0 and match_confidence <= 1),
  raw_source jsonb not null default '{}'::jsonb,
  fetched_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (medicine_id, source_system),
  unique (source_url)
);
create index if not exists idx_cipla_product_metadata_name on public.cipla_product_metadata (lower(product_name));
create index if not exists idx_cipla_product_metadata_fetched_at on public.cipla_product_metadata (fetched_at desc);
alter table public.cipla_product_metadata enable row level security;
drop policy if exists "cipla metadata authenticated read" on public.cipla_product_metadata;
create policy "cipla metadata authenticated read" on public.cipla_product_metadata for select to authenticated using (true);

create or replace view public.medicine_manufacturer_metadata as
select medicine_id,'leeford'::text source_system,'Leeford'::text manufacturer,product_name,composition,formulation,null::text therapy,null::text pack_size,null::numeric reference_mrp,status,description,source_url,match_method,match_confidence,fetched_at,updated_at,raw_source
from public.leeford_product_metadata
union all
select medicine_id,'univentis'::text,manufacturer,product_name,composition,formulation,therapy,pack_size,reference_mrp,status,description,source_url,match_method,match_confidence,fetched_at,updated_at,raw_source
from public.univentis_product_metadata
union all
select medicine_id,source_system,manufacturer,product_name,coalesce(composition,molecule),coalesce(formulation,dosage_form),therapy,pack_size,reference_mrp,status,description,coalesce(product_page_url,source_url),match_method,match_confidence,fetched_at,updated_at,raw_source
from public.cipla_product_metadata;
