-- Customer online ordering platform. Orders are requests until pharmacist confirmation.
create table if not exists public.customer_orders (
  id uuid primary key default gen_random_uuid(), order_number text not null unique,
  tracking_token text not null unique, customer_name text not null, customer_phone text not null,
  customer_email text, address_line1 text not null, address_line2 text, landmark text,
  city text not null, state text not null default 'Punjab', pincode text not null,
  delivery_method text not null default 'delivery' check (delivery_method in ('delivery','pickup')),
  notes text, subtotal numeric(12,2) not null default 0 check (subtotal >= 0),
  discount numeric(12,2) not null default 0 check (discount >= 0), delivery_fee numeric(12,2) not null default 0 check (delivery_fee >= 0),
  total numeric(12,2) not null default 0 check (total >= 0), payment_method text not null default 'cod' check (payment_method in ('cod','razorpay')),
  payment_status text not null default 'pending' check (payment_status in ('pending','paid','failed','refunded')),
  order_status text not null default 'pending_review' check (order_status in ('pending_review','confirmed','preparing','ready','out_for_delivery','delivered','cancelled','rejected')),
  prescription_status text not null default 'not_required' check (prescription_status in ('not_required','pending','approved','rejected')),
  prescription_id bigint references public.prescriptions(id) on delete set null, razorpay_order_id text unique,
  razorpay_payment_id text, sale_id bigint references public.sales(id) on delete set null,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

create table if not exists public.customer_order_items (
  id bigint generated by default as identity primary key, order_id uuid not null references public.customer_orders(id) on delete cascade,
  medicine_id text not null, medicine_name text not null, category text, quantity integer not null check (quantity > 0),
  unit_price numeric(12,2) not null check (unit_price >= 0), line_total numeric(12,2) not null check (line_total >= 0),
  batch_id bigint references public.inventory_batches(id) on delete set null, batch_no text, expiry_date date,
  created_at timestamptz not null default now()
);

create table if not exists public.customer_order_events (
  id bigint generated by default as identity primary key, order_id uuid not null references public.customer_orders(id) on delete cascade,
  status text not null, note text, created_at timestamptz not null default now()
);

alter table public.prescriptions add column if not exists order_id uuid references public.customer_orders(id) on delete set null;
create index if not exists customer_orders_created_at_idx on public.customer_orders(created_at desc);
create index if not exists customer_orders_status_idx on public.customer_orders(order_status);
create index if not exists customer_order_items_order_id_idx on public.customer_order_items(order_id);
create index if not exists customer_order_events_order_id_idx on public.customer_order_events(order_id, created_at desc);
create index if not exists prescriptions_order_id_idx on public.prescriptions(order_id);

create or replace function public.set_customer_orders_updated_at() returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end; $$;
drop trigger if exists customer_orders_updated_at on public.customer_orders;
create trigger customer_orders_updated_at before update on public.customer_orders for each row execute function public.set_customer_orders_updated_at();

alter table public.customer_orders enable row level security;
alter table public.customer_order_items enable row level security;
alter table public.customer_order_events enable row level security;
revoke all on public.customer_orders from anon, authenticated;
revoke all on public.customer_order_items from anon, authenticated;
revoke all on public.customer_order_events from anon, authenticated;


create or replace function public.confirm_customer_order(p_order_id uuid)
returns jsonb
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_order public.customer_orders%rowtype;
  v_items jsonb;
  v_result jsonb;
  v_sale_id bigint;
begin
  select * into v_order from public.customer_orders where id = p_order_id for update;
  if not found then raise exception 'Online order not found'; end if;
  if v_order.sale_id is not null then
    return jsonb_build_object('success', true, 'already_confirmed', true, 'sale_id', v_order.sale_id, 'order_id', v_order.id, 'order_status', v_order.order_status);
  end if;
  if v_order.payment_method = 'razorpay' and v_order.payment_status <> 'paid' then raise exception 'Online payment is not confirmed yet'; end if;
  if v_order.prescription_status = 'pending' then raise exception 'Prescription must be approved before confirmation'; end if;
  if v_order.prescription_status = 'rejected' then raise exception 'Order prescription was rejected'; end if;
  if v_order.order_status in ('cancelled','rejected','delivered') then raise exception 'Order cannot be confirmed from its current status'; end if;
  select coalesce(jsonb_agg(jsonb_build_object('medicine_id', medicine_id, 'quantity', quantity, 'unit_price', unit_price) order by id), '[]'::jsonb)
  into v_items from public.customer_order_items where order_id = v_order.id;
  if jsonb_array_length(v_items) = 0 then raise exception 'Online order has no items'; end if;
  v_result := public.pos_checkout(v_items, coalesce(v_order.discount, 0), case when v_order.payment_method = 'razorpay' then 'card' else 'cash' end, v_order.customer_name, v_order.customer_phone, case when v_order.payment_status = 'paid' then v_order.total else 0 end);
  v_sale_id := nullif(v_result->>'sale_id','')::bigint;
  if v_sale_id is null then raise exception 'POS checkout returned no sale ID'; end if;
  update public.customer_orders set sale_id = v_sale_id, order_status = 'confirmed', updated_at = now() where id = v_order.id;
  insert into public.customer_order_events(order_id,status,note) values(v_order.id,'confirmed','Order confirmed by pharmacy; POS sale ' || v_sale_id || ' created.');
  return v_result || jsonb_build_object('success', true, 'order_id', v_order.id, 'sale_id', v_sale_id);
end;
$$;

revoke execute on function public.confirm_customer_order(uuid) from public, anon, authenticated;
grant execute on function public.confirm_customer_order(uuid) to service_role;
