create table if not exists public.leeford_product_metadata (
  id bigint generated by default as identity primary key,
  medicine_id text not null,
  product_name text not null,
  source_url text not null,
  leeford_product_id text,
  slug text,
  composition text,
  formulation text,
  status text,
  description text,
  side_effects text,
  dosage_directions text,
  match_method text not null default 'exact_normalized_name',
  match_confidence numeric(5,4) not null default 1.0000 check (match_confidence >= 0 and match_confidence <= 1),
  raw_source jsonb not null default '{}'::jsonb,
  fetched_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (medicine_id),
  unique (source_url)
);
create index if not exists idx_leeford_product_metadata_name on public.leeford_product_metadata (lower(product_name));
create index if not exists idx_leeford_product_metadata_fetched_at on public.leeford_product_metadata (fetched_at desc);
alter table public.leeford_product_metadata enable row level security;
drop policy if exists "leeford metadata authenticated read" on public.leeford_product_metadata;
create policy "leeford metadata authenticated read" on public.leeford_product_metadata for select to authenticated using (true);
